[package]
name = "deployer"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
serde = "1.0.126"
serde_bytes = "0.11"
serde_json = "1.0.82"
sha2 = "0.10.6"
